name: Alignment


on:
  push:
    branches:
      - '**'

jobs:
  alignment:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@v1.6.3
        id: generate-token
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_KEY }}
      - uses: actions/checkout@v3
        with:
          token: ${{ steps.generate-token.outputs.token }}
      - name: Get the commit message header
        id: commit-message
        run: |
          HEADER=$(git log -1 --pretty=%B | head -n 1)
          echo "Commit message header: $HEADER"
          echo "header=$HEADER" >> $GITHUB_OUTPUT
      - name: Repository Alignment
        run: |
          gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/DemyCode/dalia/dispatches \
          -f "event_type=alignment" \
          -F "client_payload[branch]=${{ github.ref_name }}" \
          -F "client_payload[repository]=${{ github.event.repository.name }}" \
          -F "client_payload[message]=${{ steps.commit-message.outputs.header }}"
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
